name: Validate release metadata
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  validate:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt -y install jq curl
    - name: Run validation script
      run: "git rm $(find docs/metadata/vendor -name '*.json' ! -name all.json | xargs -t -P 8 -I % -n 1 bin/validate.bash %) || true"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Remove invalid release metadata
        title: Remove invalid release metadata
        base: main
        labels: automated-pr
        branch: issues/validate-metadata
        delete-branch: true
